"""empty message

Revision ID: 75cebf83ac71
Revises: 
Create Date: 2023-05-03 23:36:49.148812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cebf83ac71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_title', sa.String(length=20), nullable=False),
    sa.Column('image_description', sa.String(length=150), nullable=True),
    sa.Column('secure_url', sa.String(length=180), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
